### PR TITLE
Add 2018 constitution

### PR DESCRIPTION
**Pull request by mckelvin**
Please check https://github.com/cn/constitution/pull/2/commits/8115484d1848d309f68c709d8ea176374b2b1160?short_path=0940822#diff-0940822c6694b6d9392bc013e547fe41 for the changes mentioned in http://www.xinhuanet.com/politics/2018-02/25/c_1122451187.htm .

The purpose of the PR is to provide a `git diff` way (which is more a friendly way compared to the original proposal) to read and learn from the proposal. All rights belong to their respective owners. Please let me know if there're anything wrong or anything improper.

NOTE: The PR is still **working in progress** as the proposal is not confirmed yet, so please don't merge it in case there's a `[WIP]` prefix in the title of the PR. Code review is not needed for now, please obey the law and be responsible for your own comment if you'd like to comment. 🙂

UPDATE: The NPC approved this proposal http://www.npc.gov.cn/npc/xinwen/2018-03/12/content_2046540.htm

UPDATE: The NPC promulgated this proposal http://www.npc.gov.cn/npc/xinwen/2018-03/22/content_2052489.htm

### CODE REVIEW

**Comment by hustcc** [comment]
速度真快呀😂

**Comment by lepture** [comment]
等確定了再說

**Comment by TimonPeng** [comment]
调皮

**Comment by Altynai** [comment]
妙妙这波稳中带皮

**Comment by hehongyu1995** [comment]
牛批啊，留名

**Comment by Kyncc** [comment]
李时珍的皮

**Comment by waltcow** [comment]
Welcome to the new age, let's party like 1793

**Comment by v5b7** [comment]
真皮，哈哈哈

**Comment by dongshimou** [comment]
<<走向共和>>

**Comment by yzgyyang** [comment]
老哥稳！

**Comment by XhstormR** [comment]
吾皇万岁，万万岁！

**Comment by tonyseek** [comment]
@lepture @mckelvin IMO, we should lock this thread until the proposal be reviewed by NPC. How do you think? There are too many spam comments.

**Comment by tonyseek** [comment]
lock for now until the NPC make their decision.

**Comment by tonyseek** [comment]
Still lock until [the President of PRC promulgate the constitution (2018)](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E4%B8%BB%E5%B8%AD%E4%BB%A4).

It will be published in [the official website of NPC](http://www.npc.gov.cn/npc/xinwen/node_16265.htm).

**Pull request merged**
